# Allow sudo for running apt-get.
sudo: required
os:
  - linux
  - osx
language: cpp
compiler:
  - clang
script:
  - .travis/build.sh

before_deploy:
  - .travis/prepare-for-deploy.sh

# Upload to Google Cloud Storage.
deploy:
  provider: gcs
  access_key_id: GOOGK4FOMGQU2NF2FMEG
  # This is encrypted, see docs.travis-ci.com/user/deployment/gcs/.
  secret_access_key:
    secure: KXlQaKk1G527mZ7hC+m8rblBZrOWQJr6uPX9M5S3XpSAehBDBQ26/pwvDutbQBolsvUfd+WgsXU28JINk89B1qA4HpNax0ucveM5C1K4mC5fR5EmtCThV4MDsmirzfVmAxUMOXowUjpyYX39+f+Yy2Y6GHhftIe9WaueCYJyg0I=
  bucket: bucket-o-bazel
  local_dir: ci
  acl: public-read
  skip_cleanup: true
  on:
    branch: osx-ci
